var annotated_dup =
[
    [ "tinyxml2", null, [
      [ "DynArray", "classtinyxml2_1_1_dyn_array.html", "classtinyxml2_1_1_dyn_array" ],
      [ "Entity", "structtinyxml2_1_1_entity.html", "structtinyxml2_1_1_entity" ],
      [ "LongFitsIntoSizeTMinusOne", "structtinyxml2_1_1_long_fits_into_size_t_minus_one.html", null ],
      [ "LongFitsIntoSizeTMinusOne< false >", "structtinyxml2_1_1_long_fits_into_size_t_minus_one_3_01false_01_4.html", null ],
      [ "MemPool", "classtinyxml2_1_1_mem_pool.html", "classtinyxml2_1_1_mem_pool" ],
      [ "MemPoolT", "classtinyxml2_1_1_mem_pool_t.html", "classtinyxml2_1_1_mem_pool_t" ],
      [ "StrPair", "classtinyxml2_1_1_str_pair.html", "classtinyxml2_1_1_str_pair" ],
      [ "XMLAttribute", "classtinyxml2_1_1_x_m_l_attribute.html", "classtinyxml2_1_1_x_m_l_attribute" ],
      [ "XMLComment", "classtinyxml2_1_1_x_m_l_comment.html", "classtinyxml2_1_1_x_m_l_comment" ],
      [ "XMLConstHandle", "classtinyxml2_1_1_x_m_l_const_handle.html", "classtinyxml2_1_1_x_m_l_const_handle" ],
      [ "XMLDeclaration", "classtinyxml2_1_1_x_m_l_declaration.html", "classtinyxml2_1_1_x_m_l_declaration" ],
      [ "XMLDocument", "classtinyxml2_1_1_x_m_l_document.html", "classtinyxml2_1_1_x_m_l_document" ],
      [ "XMLElement", "classtinyxml2_1_1_x_m_l_element.html", "classtinyxml2_1_1_x_m_l_element" ],
      [ "XMLHandle", "classtinyxml2_1_1_x_m_l_handle.html", "classtinyxml2_1_1_x_m_l_handle" ],
      [ "XMLNode", "classtinyxml2_1_1_x_m_l_node.html", "classtinyxml2_1_1_x_m_l_node" ],
      [ "XMLPrinter", "classtinyxml2_1_1_x_m_l_printer.html", "classtinyxml2_1_1_x_m_l_printer" ],
      [ "XMLText", "classtinyxml2_1_1_x_m_l_text.html", "classtinyxml2_1_1_x_m_l_text" ],
      [ "XMLUnknown", "classtinyxml2_1_1_x_m_l_unknown.html", "classtinyxml2_1_1_x_m_l_unknown" ],
      [ "XMLUtil", "classtinyxml2_1_1_x_m_l_util.html", null ],
      [ "XMLVisitor", "classtinyxml2_1_1_x_m_l_visitor.html", "classtinyxml2_1_1_x_m_l_visitor" ]
    ] ],
    [ "Application", "class_application.html", "class_application" ],
    [ "Command", "class_command.html", "class_command" ],
    [ "ComponentPool", "class_component_pool.html", "class_component_pool" ],
    [ "Event", "struct_event.html", "struct_event" ],
    [ "EventSystem", "class_event_system.html", "class_event_system" ],
    [ "Game", "class_game.html", "class_game" ],
    [ "GameEvent", "struct_game_event.html", "struct_game_event" ],
    [ "GameObject", "class_game_object.html", "class_game_object" ],
    [ "IComponent", "class_i_component.html", "class_i_component" ],
    [ "IEventHandler", "class_i_event_handler.html", "class_i_event_handler" ],
    [ "InputInterpreter", "class_input_interpreter.html", "class_input_interpreter" ],
    [ "InputSystem", "class_input_system.html", "class_input_system" ],
    [ "IRenderable", "class_i_renderable.html", "class_i_renderable" ],
    [ "IResource", "class_i_resource.html", "class_i_resource" ],
    [ "IUpdatable", "class_i_updatable.html", "class_i_updatable" ],
    [ "KeyCommand", "class_key_command.html", "class_key_command" ],
    [ "MapEvent", "struct_map_event.html", "struct_map_event" ],
    [ "MapSystem", "class_map_system.html", "class_map_system" ],
    [ "MovementComponent", "class_movement_component.html", "class_movement_component" ],
    [ "MusicEvent", "struct_music_event.html", "struct_music_event" ],
    [ "MusicResource", "struct_music_resource.html", "struct_music_resource" ],
    [ "ObjectPool", "class_object_pool.html", "class_object_pool" ],
    [ "PhazeLogger", "class_phaze_logger.html", "class_phaze_logger" ],
    [ "PhysicsComponent", "struct_physics_component.html", "struct_physics_component" ],
    [ "PhysicsSystem", "class_physics_system.html", "class_physics_system" ],
    [ "ResourceSystem", "class_resource_system.html", "class_resource_system" ],
    [ "ScriptSystem", "class_script_system.html", "class_script_system" ],
    [ "SfxEvent", "struct_sfx_event.html", "struct_sfx_event" ],
    [ "SfxResource", "struct_sfx_resource.html", "struct_sfx_resource" ],
    [ "TextureComponent", "struct_texture_component.html", "struct_texture_component" ],
    [ "TextureEvent", "struct_texture_event.html", "struct_texture_event" ],
    [ "TextureResource", "struct_texture_resource.html", "struct_texture_resource" ],
    [ "Vector2D", "struct_vector2_d.html", "struct_vector2_d" ],
    [ "View", "class_view.html", "class_view" ]
];